#!/bin/python3

# this file should be executed from game launcher with proper arguments shuch as current map, current character, etc.

import pygame as pg
import os, sys, copy
from math import *
from settings.settings import *
# only for debuging remove in release
from pprint import pprint

# importing map based on cmd arguments
if sys.argv[1]== '1':
    from maps.map_1 import * # provides world, sources, bg, scale, textures
elif sys.argv[1]== '2':
    from maps.map_2 import * # provides world, sources, bg, scale, textures
elif sys.argv[1]== '3':
    from maps.map_3 import * # provides world, sources, bg, scale, textures

# inventory info
collected_keys= 0
collected_coins= 0
collected_coins_total= 0

pg.init() # allows to use pygame methods
default_font= pg.font.SysFont(font_family, default_font_size) # default font
counter_font= pg.font.SysFont(font_family, counter_font_size) # font to be used for move counter
display= pg.display.set_mode((w, h)) # creates window
fps= 60 # fps limit, this should not be changed
clock = pg.time.Clock() # clock to limit fps
moves_left= 20 # how many moves can you make

# every event that changes something on game map located in world list. Format of event_queue: [ { (text) 'action', (text) 'target', (int) 'frames', additional arguments } ] where frames is on how many frames event will execute this values is decremented every frame by event_handler()
event_queue= []

# fills background to solid color
def draw_bg():
    display.fill(bg) # change bg color of window saved in display variable

# draws every object from world list
def draw_world():
    # world[] contains every object located on current level/map
    for el in world:
        display.blit(el['texture'], (el['pos']['x'], el['pos']['y']))

# displays how many moves left for player to make
def show_move_counter():
    counter= counter_font.render(f'{moves_left}', 1, (49, 228, 201))
    display.blit(counter, (w- 50, 20))

# renders background and objects from world list and displays text
def render():
    draw_bg()
    draw_world()
    show_move_counter()

    pg.display.flip() # shows newly rendered elements

def get_player_width():
    for e in world:
        if e['obj_class']== 'player':
            return e['texture'].get_width()

def get_player_height():
    for e in world:
        if e['obj_class']== 'player':
            return e['texture'].get_height()

def get_player_x():
    for e in world:
        if e['obj_class']== 'player':
            return e['pos']['x']

def get_player_y():
    for e in world:
        if e['obj_class']== 'player':
            return e['pos']['y']

# returns array that contains player_x and player_y
def get_player_x_and_y():
    for e in world:
        if e['obj_class']== 'player':
            return [e['pos']['x'], e['pos']['y']]

# returns player object from world array
def get_player():
    for e in world:
        if e['obj_class']== 'player':
            return e

# moves viewport by moving world array content by value argument
def move_viewport(value):
    for e in world:
        e['pos']['x']+= value
        if e['colidable']== 1 or e['colidable']== -1:
            e['hitbox']= generate_hitbox(e['obj_class'], e['texture'], e['pos']['x'], e['pos']['y'])

# adds hitboxes to every object, should be executed only once
def add_hitboxes_to_every_obj():
    for e in world:
        # colidable== 1 means collisions with this object is possible, colidable== -1 means collisions aren't possible with this object but hitbox will be generated anyways
        if e['colidable']== 1 or e['colidable']== -1:
            e['hitbox']= generate_hitbox(e['obj_class'], e['texture'], e['pos']['x'], e['pos']['y'])

# generates hitbox for requested values
def generate_hitbox(obj_class, obj_texture, x, y):
    # get default rules for generating hitbox
    global_rule= hitbox_generation_rules[0]
    # get width of requested obj through its texture
    width, height= obj_texture.get_width(), obj_texture.get_height()

    # loop through every rule in rules except index 0 which is default rules set if none was specified.
    for rule_index in range(1, len(hitbox_generation_rules)):
        # if requested obj_class matches obj_class for rule change global_rule to rule on this index
        if hitbox_generation_rules[rule_index]['obj_class']== obj_class:
            global_rule= hitbox_generation_rules[rule_index]

    # calculate and return rules for requested object
    return {
            'y_top': eval(global_rule['change']['y_top']),
            'y_bot': eval(global_rule['change']['y_bot']),
            'x_left': eval(global_rule['change']['x_left']),
            'x_right': eval(global_rule['change']['x_right']),
            }

# move object from world list
def move(obj_class, speed_x, speed_y):
    for e in world:
        if e['obj_class']== obj_class:
            e_prev= {
                    'pos': copy.deepcopy(e['pos']),
                    'texture': e['texture'],
                    'colidable': e['colidable'],
                    'colidable': e['obj_class'],
                    'hitbox': generate_hitbox(e, e['texture'], e['pos']['x'], e['pos']['y']),
                    }
            collision_occured= False
            # if colidable check collisions with other objects
            if e['colidable']== 1:
                # if move right
                if speed_y== 0 and speed_x> 0:
                    # get colliding element if no collision colid_element= None
                    colid_element= check_all_collisions_with_obj(e, ['x_right'])
                    # check if collision occured
                    if colid_element!= None:
                        # move as close to colid_element in x axis as posible
                        e['pos']['x']= colid_element['hitbox']['x_left']- e['texture'].get_width()
                        collision_occured= True
                # if move left
                elif speed_y== 0 and speed_x< 0:
                    # get colliding element if no collision colid_element= None
                    colid_element= check_all_collisions_with_obj(e, ['x_left'])
                    # check if collision occured
                    if colid_element!= None:
                        # move as close to colid_element in x axis as posible
                        e['pos']['x']= colid_element['hitbox']['x_right']
                        collision_occured= True
                # if move down
                elif speed_y> 0 and speed_x== 0:
                    # get colliding element if no collision colid_element= None
                    colid_element= check_all_collisions_with_obj(e, ['y_bot'])
                    # check if collision occured
                    if colid_element!= None:
                        # move as close to colid_element in x axis as posile
                        e['pos']['y']= colid_element['hitbox']['y_top']- e['texture'].get_height()- 1
                        collision_occured= True
                # if move up
                elif speed_y< 0 and speed_x== 0:
                    # get colliding element if no collision colid_element= None
                    colid_element= check_all_collisions_with_obj(e, ['y_top'])
                    # check if collision occured
                    if colid_element!= None:
                        # move as close to colid_element in x axis as posile
                        e['pos']['y']= colid_element['hitbox']['y_bot']
                        collision_occured= True

            # if collision hasn't occured just move normaly
            if collision_occured is not True:
                # change position
                e['pos']['x']+= speed_x
                e['pos']['y']+= speed_y

            # regenerate hitbox for new position
            if e['colidable']== 1 or e['colidable']== -1:
                e['hitbox']= generate_hitbox(e['obj_class'], e['texture'], e['pos']['x'], e['pos']['y'])

# check collisions between selected object and every other object in world array
def check_all_collisions_with_obj(obj, types): # for all collisions: types= ['x_right', 'x_left', 'x_top', 'x_bot']
    for e in world:
        # if obj is not equal requested object check collisions
        if e!= obj and e['colidable']== 1:
            # if collision occured return colliding element
            if check_collision(obj, e, types):
                return e

# check collisions between selected object and every other object in world array and return every colliding object
def return_all_collisions_with_obj(obj, types): # for all collisions: types= ['x_right', 'x_left', 'x_top', 'x_bot']
    ret_val= []
    for e in world:
        # if obj is not equal requested object check collisions
        if e!= obj and e['colidable']== 1:
            # if collision occured return colliding element
            if check_collision(obj, e, types):
                ret_val.append(e)
    return ret_val

# checks and handles gravity for player
def gravity_handler():
    # player is currently moving
    event_queue_contains_player= False
    for queue in event_queue:
        # move player action is inside event_queue 
        if queue['target']== 'player':
            event_queue_contains_player= True

    # if event_queue_contains_player is not True:
    collision= check_all_collisions_with_obj(get_player(), ['y_bot'])
    if collision is not True and event_queue_contains_player is not True:
        event_queue.append({'action': 'mv', 'target': 'player', 'frames': 1, 'x': 0, 'y': gravity})

# checks collision between two objects if collision occurs returns 1 else returns 0
# types= ['y_top', 'y_bot', 'x_left', 'x_right'] for checking collisions in every direction from obj_one
def check_collision(obj_one, obj_two, types):
    obj_one_hitbox= obj_one['hitbox']
    obj_two_hitbox= obj_two['hitbox']
    obj_one_right= obj_one_hitbox['x_right']
    obj_one_left= obj_one_hitbox['x_left']
    obj_one_top= obj_one_hitbox['y_top']
    obj_one_bot= obj_one_hitbox['y_bot']

    obj_two_left= obj_two_hitbox['x_left']
    obj_two_right= obj_two_hitbox['x_right']
    obj_two_top= obj_two_hitbox['y_top']
    obj_two_bot= obj_two_hitbox['y_bot']

    if 'x_right' in types:
        b_x_collision= obj_one_right>= obj_two_left and obj_one_right< obj_two_right
        b_y_collision= obj_one_top<= obj_two_bot and obj_one_bot>= obj_two_top

        if b_x_collision and b_y_collision:
            return True
    if 'x_left' in types:
        b_x_collision= obj_one_left<= obj_two_right and obj_one_left> obj_two_left
        b_y_collision= obj_one_top<= obj_two_bot and obj_one_bot>= obj_two_top

        if b_x_collision and b_y_collision:
            return True
    if 'y_top' in types:
        b_x_collision= obj_one_left>= obj_two_left and obj_one_left<= obj_two_right or obj_two_left>= obj_one_left and obj_two_left<= obj_one_right
        b_y_collision= obj_one_top<= obj_two_bot and obj_one_bot>= obj_two_bot

        if b_x_collision and b_y_collision:
            return True
    if 'y_bot' in types:
        b_x_collision= obj_one_left>= obj_two_left and obj_one_left<= obj_two_right or obj_two_left>= obj_one_left and obj_two_left<= obj_one_right
        b_y_collision= obj_one_bot>= obj_two_top- 1 and obj_one_top<= obj_two_top

        if b_x_collision and b_y_collision:
            return True
    return False

# check if distance from player to screen border is lesser than minimum_distance_from_border and moves viewport if true
def check_distance_from_screen_border():
    player_x= get_player_x()
    distance_from_left_border= player_x
    distance_from_right_border= w- (player_x+ get_player_width())

    if distance_from_left_border<= minimum_distance_from_border:
        move_viewport(viewport_movement_value)
    if distance_from_right_border<= minimum_distance_from_border:
        move_viewport(-viewport_movement_value)

# executes single event from event_queue
def exec_event(ev):
    if ev['action']== 'mv':
        move(ev['target'], ev['x'], ev['y'])

# handles/executes events from event_queue
def event_handler():
    delete_marks= []
    for ev in event_queue:
        ev['frames']-= 1
        exec_event(ev)
        if ev['frames']<= 0:
            delete_marks.append(ev)
    for ev in delete_marks:
        event_queue.remove(ev)

# check if key has been pressed and exec its action
def check_keys():
    # loop through pygame events such as keyboard events
    # put key shortcuts in this loop
    for event in pg.event.get():
        if event.type== pg.QUIT: sys.exit()
        if event.type== pg.KEYDOWN:
            if event.key== pg.K_d:
                # i have no idea why this globals() is necessary but if you remove it game will crash
                globals()['moves_left']-= 1
                event_queue.append({'action': 'mv', 'target': 'player', 'frames': 20, 'x': player_speed, 'y': 0})
            if event.key== pg.K_a:
                globals()['moves_left']-= 1
                event_queue.append({'action': 'mv', 'target': 'player', 'frames': 20, 'x': -player_speed, 'y': 0})
            if event.key== pg.K_SPACE:
                globals()['moves_left']-= 1
                event_queue.append({'action': 'mv', 'target': 'player', 'frames': 20, 'x': 0, 'y': -player_speed})

# checks collisions with collectable items such as keys, coins, etc...
def check_collectables():
    delete_marks= []
    for e in world:
        if e['obj_class']== 'key' and e['colidable']== 1 or e['obj_class']== 'key' and e['colidable']== -1:
            if get_player() in return_all_collisions_with_obj(e, ['x_left', 'x_right', 'y_top', 'y_bot']):
                delete_marks.append(e)
                # i have no idea why this globals() is necessary but if you remove it game will crash
                globals()['collected_keys']+= 1
                print('Player collected key, collected_keys=', collected_keys)
    for e in delete_marks:
        world.remove(e)

# executes before render function
def prerender():
    check_keys() # check if some binded key has been pressed and do some action/event
    gravity_handler() # handles object's gravity
    event_handler() # executes events from event_queue
    check_collectables() # checks collisions with collectable items such as keys, coins, etc...
    check_distance_from_screen_border() # check if player's distance to border is lesser than minimum_distance_from_border and if that is true moves viewport by moving world's content

# check if player still have some moves left
def check_if_player_lost_because_of_moves_count():
    b_player_event_in_queue= False
    # check if player movement still can change because of events from event_queue with target= 'player'
    for ev in event_queue:
        if ev['target']== 'player':
            b_player_event_in_queue= True

    if moves_left<= 0 and b_player_event_in_queue is False: return True
    else: return False

if __name__== '__main__':
    add_hitboxes_to_every_obj()
    # game loop
    while True:
        clock.tick(fps) # limits fps to value of fps variable
        prerender() # handling hotkeys, event_queue, etc.
        render() # draws objects and background

        # check if player lost the game
        if check_if_player_lost_because_of_moves_count():
            sys.exit()
